# fly.toml app configuration file generated for fastzeroapp-0001 on 2024-09-10T07:01:57-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fastzeroapp-0001'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
